# Uncomment the next line to define a global platform for your project
 platform :macos, '10.12'

target 'mac43' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for mac43
  pod 'AFNetworking', '~> 3.0'
end
